### ISSUE TITLE
Refactor Github action for Acceptance Testing

### ISSUE THREAD

**Issue by jaredgalanis** [eclipse-pass/main#399]
https://github.com/eclipse-pass/pass-docker/blob/main/.github/workflows/workflow.yml#L4

The syntax here needs to be updated to snake case `pull_request` instead of the dasherized case that's currently used.

See, https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request.

I think also we should rename the file to something more specific such as `pass-acceptance-tests.yml`. 

Once these fixes are in, we should be able to run the workflow manually prior to merging to see how things are running.

**Comment by jabrah** [comment]
Looks like there's still a syntax error in the action. The job needs a `runs-on` prop to say where the job should run. This should go between the current lines 9 and 10, so should look like:

``` yml
jobs:
  run_acceptance_tests:
    runs-on: ubuntu-latest  # Added line
    steps:
    - name: Checkout pass-docker
```

Docs for this property: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on

GH provides some options for Windows, Linux, and MacOS. I tend to lean towards Linux, personally, since we'll ultimately be deploying in a Linux or Linux-like environment and we don't have a current pressing need to test in other operating systems

**Comment by jabrah** [comment]
Now that it looks like we're good as far as the Action syntax they are running and we can actually spot errors. Looks like we need to do a docker compose pull before the docker compose up:

Since we've had several iterations on this already, I'd be cool with appending this change onto your currently open PR, adjusting its scope a bit.

(https://github.com/frogfoot9013/pass-docker/blob/main/.github/workflows/pass-acceptance-tests.yml#L27-L28)

Something like this should work
``` yaml
run: |
        docker-compose pull
        docker-compose up -d

## OR ##

- name: Pull pass-docker
  run: |
    docker-compose pull

- name: Run pass-docker
  run: |
    docker-compose up -d
```
